import type{ReportDefinition,ReportDelivery,ReportSnapshot}from"./types";
const sections=[{id:"summary",titleAr:"المؤشرات",kind:"metrics"as const},{id:"details",titleAr:"التفاصيل",kind:"table"as const}];const common={requiredPermission:"reports.view"as const,allowedPeriods:["daily","weekly","monthly","custom"]as const,allowedFilters:["period","from","to","branch","employee","status","type","compare"],exportFormats:["print","json","csv"]as const,sections};
export const REPORT_DEFINITIONS:readonly ReportDefinition[]=[
 {key:"management-summary",nameAr:"ملخص الإدارة",descriptionAr:"مؤشرات النشاط والمالية والتشغيل والفروع.",category:"إدارة",sensitive:true,...common},
 {key:"sales",nameAr:"المبيعات",descriptionAr:"الفواتير والمرتجعات والمنتجات وأداء البيع.",category:"مبيعات",sensitive:false,...common},
 {key:"rentals",nameAr:"التأجير",descriptionAr:"التأجيرات والإيرادات والمدد والتذكيرات اليدوية.",category:"تشغيل",sensitive:false,...common},
 {key:"maintenance",nameAr:"الصيانة",descriptionAr:"البلاغات والأوامر والفنيون وقطع الغيار.",category:"صيانة",sensitive:false,...common},
 {key:"inventory",nameAr:"المخزون",descriptionAr:"الأرصدة والمنخفض والتكلفة والقيمة والأصول.",category:"مخزون",sensitive:true,...common},
 {key:"transfers",nameAr:"التحويلات",descriptionAr:"حالات التحويل والفروقات والاستلام.",category:"مخزون",sensitive:false,...common},
 {key:"finance",nameAr:"الحسابات والخزائن",descriptionAr:"الأرصدة والحركات وطرق الدفع والعكس.",category:"مالية",sensitive:true,...common},
 {key:"shifts",nameAr:"الورديات والتحصيلات",descriptionAr:"الورديات المفتوحة والمغلقة والفروقات.",category:"مالية",sensitive:true,...common},
 {key:"receivables",nameAr:"المديونيات",descriptionAr:"المبالغ المفتوحة والسداد الجزئي والمتأخر.",category:"مالية",sensitive:true,...common},
 {key:"expenses",nameAr:"المصروفات",descriptionAr:"الطلبات والموافقات والمدفوع والمعكوس.",category:"مالية",sensitive:true,...common},
 {key:"payroll",nameAr:"الرواتب",descriptionAr:"الدورات والبدلات والخصومات والسلف.",category:"مالية",sensitive:true,...common},
 {key:"attendance",nameAr:"الحضور والانصراف",descriptionAr:"الحضور والتأخير والغياب والاستثناءات.",category:"موظفون وحضور",sensitive:true,...common},
 {key:"employees",nameAr:"الموظفون",descriptionAr:"الأدوار الخمسة وتعدد الأدوار وحالة الموظفين.",category:"موظفون وحضور",sensitive:true,...common},
 {key:"branches",nameAr:"أداء الفروع",descriptionAr:"مقارنة التشغيل والموظفين والمخزون بين الفروع.",category:"إدارة",sensitive:true,...common},
 {key:"customers",nameAr:"العملاء",descriptionAr:"عدد العملاء ونشاطهم والمديونيات المرتبطة.",category:"إدارة",sensitive:true,...common},
];
const fixturePayload={reportKey:"management-summary",generatedAt:"2026-08-06T21:00:00+03:00",sections:[{id:"summary",title:"المؤشرات",kind:"metrics"as const,metrics:[{key:"sales",label:"المبيعات",value:"15792.50",unit:"ج.م"}],rows:[],summaryText:"نسخة تجريبية ثابتة"}]};
const snap=(id:string,number:string,status:ReportSnapshot["status"],period:ReportSnapshot["periodType"],creator:string):ReportSnapshot=>({id,snapshotNumber:number,reportKey:"management-summary",title:"ملخص الإدارة",periodType:period,dateFrom:"2026-08-01",dateTo:"2026-08-06",filters:{branch:"all"},branchIds:["all"],payload:fixturePayload,summary:fixturePayload.sections[0].metrics,contentHash:`hash-${id}`,version:1,createdByEmployeeId:creator,createdAt:"2026-08-06T21:00:00+03:00",immutable:true,status,idempotencyKey:`fixture-${id}`});
export const REPORT_SNAPSHOT_FIXTURES:readonly ReportSnapshot[]=[snap("snapshot-ready","RPT-2026-0001","ready","daily","employee-manager"),snap("snapshot-sent","RPT-2026-0002","sent","weekly","employee-manager"),snap("snapshot-opened","RPT-2026-0003","sent","monthly","employee-manager"),snap("snapshot-custom","RPT-2026-0004","ready","custom","employee-owner")];
export const REPORT_DELIVERY_FIXTURES:readonly ReportDelivery[]=[{id:"delivery-unread",deliveryNumber:"DLV-2026-0001",snapshotId:"snapshot-sent",senderEmployeeId:"employee-manager",recipientOwnerEmployeeId:"employee-owner",channel:"in_app",status:"sent",sentAt:"2026-08-06T21:05:00+03:00",openedAt:null,failedAt:null,failureReason:"",retryCount:0,lastRetryAt:null,idempotencyKey:"delivery-sent",createdAt:"2026-08-06T21:05:00+03:00",note:"التقرير الأسبوعي للمتابعة"},{id:"delivery-opened",deliveryNumber:"DLV-2026-0002",snapshotId:"snapshot-opened",senderEmployeeId:"employee-manager",recipientOwnerEmployeeId:"employee-owner",channel:"in_app",status:"opened",sentAt:"2026-08-01T10:00:00+03:00",openedAt:"2026-08-01T11:00:00+03:00",failedAt:null,failureReason:"",retryCount:0,lastRetryAt:null,idempotencyKey:"delivery-opened",createdAt:"2026-08-01T10:00:00+03:00",note:"تقرير شهري"},{id:"delivery-failed",deliveryNumber:"DLV-2026-0003",snapshotId:"snapshot-ready",senderEmployeeId:"employee-manager",recipientOwnerEmployeeId:"employee-owner",channel:"in_app",status:"failed",sentAt:null,openedAt:null,failedAt:"2026-08-06T21:10:00+03:00",failureReason:"فشل Mock متعمد لاختبار إعادة المحاولة",retryCount:0,lastRetryAt:null,idempotencyKey:"delivery-failed",createdAt:"2026-08-06T21:10:00+03:00",note:"سيناريو فشل"}];

