import type{InventoryTransfer,TransferItem,TransferStatus,TransferType}from"./types";
const now="2026-08-06T17:00:00+03:00";const item=(id:number,itemType:TransferItem["itemType"],productId:string|null,assetId:string|null,requested=2,received=requested):TransferItem=>({id:`transfer-item-${id}`,itemType,productId,rentalAssetId:assetId,quantityRequested:requested,quantityApproved:requested,quantityDispatched:requested,quantityReceived:received,conditionAtDispatch:"سليم ومغلف",conditionAtReceipt:received===requested?"سليم":"فرق موثق",note:"عنصر تحويل Mock"});
const rows:readonly [TransferType,string,string,TransferStatus,TransferItem,string|null][]=[
 ["branch_stock","main","branch-2","pending_approval",item(1,"stock_product","product-car-12v",null,2,0),null],
 ["workshop_parts","main","workshop","approved",item(2,"stock_product","part-battery-12v",null,4,0),"maintenance-order-5"],
 ["rental_asset","main","branch-2","requested",item(3,"rental_asset",null,"asset-scooter-01",1,0),null],
 ["maintenance_to_workshop","branch-2","workshop","in_transit",item(4,"maintenance_item",null,null,1,0),"maintenance-order-7"],
 ["maintenance_return","workshop","main","preparing",item(5,"rental_asset",null,"asset-race-workshop",1,0),"maintenance-order-8"],
 ["branch_stock","branch-2","main","partially_received",item(6,"stock_product","part-charger-12v",null,5,3),null],
 ["branch_stock","main","branch-3","difference_review",item(7,"stock_product","part-controller",null,3,2),null],
 ["branch_stock","main","branch-2","completed",item(8,"stock_product","product-bike-red",null,1,1),null],
 ["branch_stock","branch-3","main","rejected",item(9,"stock_product","product-drift-blue",null,1,0),null],
 ["workshop_parts","branch-2","workshop","cancelled",item(10,"stock_product","part-motor-550",null,1,0),"maintenance-order-3"],
];
export const TRANSFER_FIXTURES:readonly InventoryTransfer[]=rows.map(([transferType,source,destination,status,transferItem,maintenance],index)=>({id:`transfer-${index+1}`,transferNumber:`TRF-2026-${String(index+1).padStart(6,"0")}`,transferType,sourceLocationId:source,destinationLocationId:destination,requestedByEmployeeId:index%2?"employee-rental":"employee-sales",approvedByEmployeeId:["approved","preparing","in_transit","partially_received","difference_review","completed"].includes(status)?"employee-manager":null,dispatchedByEmployeeId:["in_transit","partially_received","difference_review","completed"].includes(status)?"employee-manager":null,receivedByEmployeeId:["partially_received","difference_review","completed"].includes(status)?"employee-manager":null,status,reason:"احتياج تشغيلي موثق",notes:"سيناريو تحويل",requestedAt:now,approvedAt:null,dispatchedAt:null,receivedAt:null,cancelledAt:status==="cancelled"?now:null,cancellationReason:status==="cancelled"?"أُلغي الاحتياج": "",items:[transferItem],differences:["partially_received","difference_review"].includes(status)?[{id:`difference-${index+1}`,transferItemId:transferItem.id,kind:index%2?"damaged":"shortage",quantity:Math.abs(transferItem.quantityDispatched-transferItem.quantityReceived),reason:"فرق استلام",decision:"",reviewedByEmployeeId:null,reviewedAt:null}]:[],relatedMaintenanceOrderId:maintenance,relatedRentalAssetId:transferItem.rentalAssetId,idempotencyKey:`transfer-fixture-${index+1}`,events:[{id:`transfer-event-${index+1}`,type:"fixture",at:now,by:"mock-seed",previousStatus:"",newStatus:status,reason:"سيناريو تحويل"}],createdAt:now,updatedAt:now}));
