import type { Employee, EmployeeRoleAssignment } from "./types";
import type { RoleId } from "@/permissions/types";

const at = "2026-08-01T09:00:00+03:00";
const assignment = (roleKey: RoleId, branchIds: "all" | string[]): EmployeeRoleAssignment => ({ roleKey, branchIds, active: true, assignedAt: at, assignedBy: "مالك النشاط — Mock" });
const statusHistory = (status: Employee["status"], id: string) => [{ id: `status-${id}-1`, status, reason: status === "active" ? "تفعيل السجل التجريبي" : "مراجعة إدارية تجريبية", at, by: "مدير النظام — Mock" }];

export const EMPLOYEE_FIXTURES: readonly Employee[] = [
  { id: "employee-owner", employeeNumber: "EMP-0001", userId: "user-owner", name: "أحمد فؤاد", phone: "01000000001", alternatePhone: "", email: "owner@example.test", nationalIdLast4: "1001", jobTitle: "مالك النشاط", status: "active", primaryBranchId: "main", assignedBranchIds: ["main", "branch-2", "branch-3", "workshop"], roleAssignments: [assignment("owner", "all")], hireDate: "2022-01-01", employmentType: "full_time", emergencyContactName: "جهة اتصال", emergencyContactPhone: "01000990001", address: "القاهرة", notes: "حساب المالك.", createdAt: "2022-01-01T09:00:00+02:00", updatedAt: at, lastActiveAt: "2026-08-05T15:10:00+03:00", statusHistory: statusHistory("active", "owner") },
  { id: "employee-manager", employeeNumber: "EMP-0002", userId: "user-manager", name: "منى سامح", phone: "01000000002", alternatePhone: "01200000002", email: "manager@example.test", nationalIdLast4: "1002", jobTitle: "مدير النشاط", status: "active", primaryBranchId: "main", assignedBranchIds: ["main", "branch-2", "branch-3", "workshop"], roleAssignments: [assignment("manager", "all")], hireDate: "2023-02-10", employmentType: "full_time", emergencyContactName: "جهة اتصال", emergencyContactPhone: "01000990002", address: "الجيزة", notes: "حساب المدير.", createdAt: "2023-02-10T09:00:00+02:00", updatedAt: at, lastActiveAt: "2026-08-05T14:45:00+03:00", statusHistory: statusHistory("active", "manager") },
  { id: "employee-rental", employeeNumber: "EMP-0003", userId: "user-rental", name: "كريم رجب التجريبي", phone: "01000000003", alternatePhone: "", email: "rental@example.test", nationalIdLast4: "1003", jobTitle: "موظف تأجير واستلام صيانة", status: "active", primaryBranchId: "main", assignedBranchIds: ["main", "branch-2"], roleAssignments: [assignment("rental_maintenance_employee", ["main", "branch-2"])], hireDate: "2024-01-15", employmentType: "full_time", emergencyContactName: "اتصال تجريبي", emergencyContactPhone: "01000990003", address: "عنوان تجريبي — القاهرة", notes: "", createdAt: "2024-01-15T09:00:00+02:00", updatedAt: at, lastActiveAt: "2026-08-05T14:25:00+03:00", statusHistory: statusHistory("active", "rental") },
  { id: "employee-sales", employeeNumber: "EMP-0004", userId: "user-sales", name: "سارة عادل التجريبية", phone: "01000000004", alternatePhone: "", email: "sales@example.test", nationalIdLast4: "1004", jobTitle: "موظف مبيعات", status: "active", primaryBranchId: "branch-2", assignedBranchIds: ["main", "branch-2", "branch-3"], roleAssignments: [assignment("sales_employee", ["main", "branch-2", "branch-3"])], hireDate: "2024-03-20", employmentType: "full_time", emergencyContactName: "اتصال تجريبي", emergencyContactPhone: "01000990004", address: "عنوان تجريبي — القاهرة", notes: "", createdAt: "2024-03-20T09:00:00+02:00", updatedAt: at, lastActiveAt: "2026-08-05T14:15:00+03:00", statusHistory: statusHistory("active", "sales") },
  { id: "employee-technician", employeeNumber: "EMP-0005", userId: "user-technician", name: "يوسف ماهر التجريبي", phone: "01000000005", alternatePhone: "", email: "technician@example.test", nationalIdLast4: "1005", jobTitle: "فني صيانة", status: "active", primaryBranchId: "workshop", assignedBranchIds: ["workshop"], roleAssignments: [assignment("maintenance_technician", ["workshop"])], hireDate: "2024-05-01", employmentType: "full_time", emergencyContactName: "اتصال فني تجريبي", emergencyContactPhone: "01000990005", address: "عنوان تجريبي — القاهرة", notes: "", createdAt: "2024-05-01T09:00:00+03:00", updatedAt: at, lastActiveAt: "2026-08-05T13:55:00+03:00", statusHistory: statusHistory("active", "technician") },
  { id: "employee-dual", employeeNumber: "EMP-0006", userId: "user-dual", name: "ليلى أمين التجريبية", phone: "01000000006", alternatePhone: "", email: "dual@example.test", nationalIdLast4: "1006", jobTitle: "موظف تشغيل متعدد المهام", status: "active", primaryBranchId: "branch-3", assignedBranchIds: ["branch-2", "branch-3"], roleAssignments: [assignment("rental_maintenance_employee", ["branch-2", "branch-3"]), assignment("sales_employee", ["branch-2", "branch-3"])], hireDate: "2025-01-12", employmentType: "part_time", emergencyContactName: "اتصال تجريبي", emergencyContactPhone: "01000990006", address: "عنوان تجريبي — الجيزة", notes: "تعدد أدوار صريح.", createdAt: "2025-01-12T09:00:00+02:00", updatedAt: at, lastActiveAt: "2026-08-05T12:40:00+03:00", statusHistory: statusHistory("active", "dual") },
  { id: "employee-suspended", employeeNumber: "EMP-0007", userId: "user-suspended", name: "طارق نبيل التجريبي", phone: "01000000007", alternatePhone: "", email: "suspended@example.test", nationalIdLast4: "1007", jobTitle: "موظف مبيعات مؤقت", status: "suspended", primaryBranchId: "branch-3", assignedBranchIds: ["branch-3"], roleAssignments: [assignment("sales_employee", ["branch-3"])], hireDate: "2025-06-01", employmentType: "temporary", emergencyContactName: "اتصال تجريبي", emergencyContactPhone: "01000990007", address: "عنوان تجريبي — القاهرة", notes: "إيقاف تجريبي فقط.", createdAt: "2025-06-01T09:00:00+03:00", updatedAt: at, lastActiveAt: "2026-07-28T11:00:00+03:00", statusHistory: statusHistory("suspended", "suspended") },
];

let selectedPreviewEmployee: Employee | null = null;

export function setPreviewEmployeeSelection(employee: Employee | null) {
  selectedPreviewEmployee = employee;
}

export function resolvePreviewEmployee(roles: readonly RoleId[], employees: readonly Employee[] = EMPLOYEE_FIXTURES) {
  if (selectedPreviewEmployee?.status === "active") return selectedPreviewEmployee;
  const id = roles.includes("owner") ? "employee-owner" : roles.includes("manager") ? "employee-manager" : roles.includes("rental_maintenance_employee") && roles.includes("sales_employee") ? "employee-dual" : roles.includes("sales_employee") ? "employee-sales" : roles.includes("rental_maintenance_employee") ? "employee-rental" : "employee-technician";
  return employees.find((employee) => employee.id === id) ?? EMPLOYEE_FIXTURES.find((employee) => employee.id === id) ?? EMPLOYEE_FIXTURES[0];
}
