import type{Cashbox,FinanceNotification,Payment,Receivable,Voucher}from"./types";
const now="2026-08-06T18:30:00+03:00";
export const CASHBOX_FIXTURES:readonly Cashbox[]=[
 {id:"cash-main",code:"BR01-CASH",name:"خزينة نقدية — الرئيسي",branchId:"main",type:"branch_cash",status:"active",currentBalance:28450,currency:"EGP",assignedEmployeeIds:["employee-sales","employee-rental","employee-dual"],allowNegativeBalance:false,createdAt:now,updatedAt:now},
 {id:"card-main",code:"BR01-CARD",name:"حساب بطاقات — الرئيسي",branchId:"main",type:"branch_card",status:"active",currentBalance:19600,currency:"EGP",assignedEmployeeIds:["employee-sales","employee-rental"],allowNegativeBalance:false,createdAt:now,updatedAt:now},
 {id:"wallet-main",code:"BR01-WLT",name:"محفظة إلكترونية — الرئيسي",branchId:"main",type:"branch_wallet",status:"active",currentBalance:8250,currency:"EGP",assignedEmployeeIds:["employee-sales","employee-rental"],allowNegativeBalance:false,createdAt:now,updatedAt:now},
 {id:"cash-branch-2",code:"BR02-CASH",name:"خزينة نقدية — فرع 2",branchId:"branch-2",type:"branch_cash",status:"active",currentBalance:17380,currency:"EGP",assignedEmployeeIds:["employee-sales","employee-rental","employee-dual"],allowNegativeBalance:false,createdAt:now,updatedAt:now},
 {id:"card-branch-2",code:"BR02-CARD",name:"حساب بطاقات — فرع 2",branchId:"branch-2",type:"branch_card",status:"active",currentBalance:12400,currency:"EGP",assignedEmployeeIds:["employee-sales","employee-dual"],allowNegativeBalance:false,createdAt:now,updatedAt:now},
 {id:"cash-branch-3",code:"BR03-CASH",name:"خزينة نقدية — فرع 3",branchId:"branch-3",type:"branch_cash",status:"locked",currentBalance:6900,currency:"EGP",assignedEmployeeIds:["employee-sales","employee-dual"],allowNegativeBalance:false,createdAt:now,updatedAt:now},
 {id:"cash-workshop",code:"WRK-CASH",name:"خزينة نقدية — الورشة",branchId:"workshop",type:"branch_cash",status:"active",currentBalance:18500,currency:"EGP",assignedEmployeeIds:["employee-technician","employee-manager"],allowNegativeBalance:false,createdAt:now,updatedAt:now},
 {id:"central-cash",code:"CTR-CASH",name:"الخزينة المركزية",branchId:"main",type:"central_cash",status:"active",currentBalance:95000,currency:"EGP",assignedEmployeeIds:["employee-owner","employee-manager"],allowNegativeBalance:false,createdAt:now,updatedAt:now},
];
const part=(id:string,method:"cash"|"card"|"electronic_wallet",amount:number,reference="")=>({id:`part-${id}`,method,amount,reference});
export const PAYMENT_FIXTURES:readonly Payment[]=[
 {id:"fin-pay-1",paymentNumber:"PAY-2026-0001",branchId:"main",cashboxId:"cash-main",shiftId:"shift-sales-open",customerId:"customer-001",sourceType:"sale",sourceId:"sale-401",direction:"incoming",method:"cash",parts:[part("1","cash",9380)],amount:9380,currency:"EGP",reference:"SAL-2026-0401",receivedByEmployeeId:"employee-sales",status:"completed",paidAt:now,reversedPaymentId:null,idempotencyKey:"fixture-pay-1",administrativeReason:"",createdAt:now},
 {id:"fin-pay-2",paymentNumber:"PAY-2026-0002",branchId:"branch-2",cashboxId:"card-branch-2",shiftId:"shift-sales-open",customerId:"customer-002",sourceType:"sale",sourceId:"sale-402",direction:"incoming",method:"card",parts:[part("2","card",6412.5,"CARD-402")],amount:6412.5,currency:"EGP",reference:"SAL-2026-0402",receivedByEmployeeId:"employee-sales",status:"completed",paidAt:now,reversedPaymentId:null,idempotencyKey:"fixture-pay-2",administrativeReason:"",createdAt:now},
 {id:"fin-pay-3",paymentNumber:"PAY-2026-0003",branchId:"main",cashboxId:"cash-main",shiftId:"shift-rental-open",customerId:"customer-001",sourceType:"rental",sourceId:"rental-active-15",direction:"incoming",method:"cash",parts:[part("3","cash",30)],amount:30,currency:"EGP",reference:"RNT-2026-0101",receivedByEmployeeId:"employee-rental",status:"completed",paidAt:now,reversedPaymentId:null,idempotencyKey:"fixture-pay-3",administrativeReason:"",createdAt:now},
 {id:"fin-pay-4",paymentNumber:"PAY-2026-0004",branchId:"branch-2",cashboxId:"cash-branch-2",shiftId:"shift-sales-open",customerId:"customer-010",sourceType:"sale",sourceId:"sale-403",direction:"incoming",method:"mixed",parts:[part("4a","cash",1500),part("4b","electronic_wallet",1400,"WLT-403")],amount:2900,currency:"EGP",reference:"SAL-2026-0403",receivedByEmployeeId:"employee-sales",status:"completed",paidAt:now,reversedPaymentId:null,idempotencyKey:"fixture-pay-4",administrativeReason:"",createdAt:now},
 {id:"fin-pay-5",paymentNumber:"PAY-2026-0005",branchId:"main",cashboxId:"cash-main",shiftId:"shift-rental-open",customerId:"customer-005",sourceType:"maintenance",sourceId:"maintenance-order-4",direction:"incoming",method:"cash",parts:[part("5","cash",700)],amount:700,currency:"EGP",reference:"MNT-2026-0004",receivedByEmployeeId:"employee-rental",status:"completed",paidAt:now,reversedPaymentId:null,idempotencyKey:"fixture-pay-5",administrativeReason:"",createdAt:now},
 {id:"fin-pay-old",paymentNumber:"PAY-2026-0007",branchId:"main",cashboxId:"cash-main",shiftId:null,customerId:null,sourceType:"administrative",sourceId:"admin-old",direction:"incoming",method:"cash",parts:[part("7","cash",500)],amount:500,currency:"EGP",reference:"ADM-OLD",receivedByEmployeeId:"employee-manager",status:"reversed",paidAt:now,reversedPaymentId:"fin-pay-reversal",idempotencyKey:"fixture-pay-old",administrativeReason:"تحصيل إداري",createdAt:now},
 {id:"fin-pay-reversal",paymentNumber:"PAY-2026-0008",branchId:"main",cashboxId:"cash-main",shiftId:null,customerId:null,sourceType:"refund",sourceId:"fin-pay-old",direction:"outgoing",method:"cash",parts:[part("8","cash",500)],amount:500,currency:"EGP",reference:"REV-PAY-2026-0007",receivedByEmployeeId:"employee-manager",status:"completed",paidAt:now,reversedPaymentId:"fin-pay-old",idempotencyKey:"fixture-reversal",administrativeReason:"عكس حركة تجريبية خاطئة",createdAt:now},
];
export const RECEIVABLE_FIXTURES:readonly Receivable[]=[
 {id:"recv-sale",customerId:"customer-003",branchId:"main",sourceType:"sale",sourceId:"sale-404",originalAmount:500,paidAmount:150,remainingAmount:350,dueDate:"2026-08-10",status:"partially_paid",lastPaymentAt:now,createdAt:now,updatedAt:now},
 {id:"recv-rental",customerId:"customer-001",branchId:"branch-2",sourceType:"rental",sourceId:"rental-open",originalAmount:143.1,paidAmount:100,remainingAmount:43.1,dueDate:"2026-08-07",status:"open",lastPaymentAt:null,createdAt:now,updatedAt:now},
 {id:"recv-maintenance",customerId:"customer-005",branchId:"main",sourceType:"maintenance",sourceId:"maintenance-order-4",originalAmount:1800,paidAmount:700,remainingAmount:1100,dueDate:"2026-08-09",status:"partially_paid",lastPaymentAt:now,createdAt:now,updatedAt:now},
];
export const VOUCHER_FIXTURES:readonly Voucher[]=[{id:"voucher-transfer",voucherNumber:"BR01-TRF-000001",type:"transfer",branchId:"main",cashboxId:"cash-main",destinationCashboxId:"central-cash",customerId:null,employeeId:null,amount:2000,reason:"توريد نقدية للخزينة المركزية",referenceType:"cashbox_transfer",referenceId:"transfer-cash-1",status:"completed",createdBy:"employee-manager",approvedBy:"employee-owner",createdAt:now,approvedAt:now,reversedAt:null,reversalReason:"",idempotencyKey:"fixture-voucher-transfer"}];
export const FINANCE_NOTIFICATION_FIXTURES:readonly FinanceNotification[]=[
 {id:"fin-note-1",type:"shift_review",title:"وردية بعجز تنتظر المراجعة",href:"/shifts/shift-shortage",createdAt:now,read:false},
 {id:"fin-note-2",type:"cashbox_locked",title:"خزينة فرع 3 مقفلة",href:"/finance/cashboxes",createdAt:now,read:false},
];
