import{getOpenShift}from"@/features/shifts/services/shift-store";import{CASHBOX_FIXTURES,FINANCE_NOTIFICATION_FIXTURES,PAYMENT_FIXTURES,RECEIVABLE_FIXTURES,VOUCHER_FIXTURES}from"../fixtures";import{isFinanceAdmin}from"../permissions";import{validatePayment}from"../schemas/finance-schema";import type{Cashbox,FinanceSnapshot,Payment,RecordPaymentInput,Receivable,Voucher,VoucherType}from"../types";import{readLocalTestData,removeLocalTestData,writeLocalTestData}from"@/lib/local-test-data";
const STORAGE_KEY="l3bty-local-finance-v1",STORAGE_VERSION=1,NOW="2026-08-06T19:00:00+03:00";const stored=readLocalTestData<FinanceSnapshot&{sequence:number}>(STORAGE_KEY,STORAGE_VERSION,{cashboxes:[],payments:[],vouchers:[],receivables:[],audits:[],notifications:[],sequence:200});let cashboxes:readonly Cashbox[]=stored.cashboxes.map((item)=>({...item,assignedEmployeeIds:[...item.assignedEmployeeIds]}));let payments:readonly Payment[]=stored.payments.map(clonePayment);let vouchers:readonly Voucher[]=stored.vouchers.map((item)=>({...item}));let receivables:readonly Receivable[]=stored.receivables.map((item)=>({...item}));let audits:FinanceSnapshot["audits"]=stored.audits.map((item)=>({...item}));let notifications=stored.notifications.map((item)=>({...item}));let sequence=stored.sequence;let snapshot:FinanceSnapshot={cashboxes,payments,vouchers,receivables,audits,notifications};const listeners=new Set<()=>void>();
function clonePayment(item:Payment):Payment{return{...item,parts:item.parts.map((part)=>({...part}))}}function emit(){snapshot={cashboxes,payments,vouchers,receivables,audits,notifications};writeLocalTestData(STORAGE_KEY,STORAGE_VERSION,{...snapshot,sequence});listeners.forEach((listener)=>listener())}export function subscribeFinanceStore(listener:()=>void){listeners.add(listener);return()=>listeners.delete(listener)}export function getFinanceSnapshot(){return snapshot}
export function createDefaultCashboxForBranch(branch:{id:string;code:string;name:string}){const existing=cashboxes.find((item)=>item.branchId===branch.id&&item.type==="branch_cash");if(existing)return existing;const now=new Date().toISOString();const cashbox:Cashbox={id:`cash-${branch.id}`,code:`${branch.code}-CASH`,name:`خزينة نقدية — ${branch.name}`,branchId:branch.id,type:"branch_cash",status:"active",currentBalance:0,currency:"EGP",assignedEmployeeIds:["employee-owner","employee-manager","employee-rental","employee-sales"],allowNegativeBalance:false,createdAt:now,updatedAt:now};cashboxes=[cashbox,...cashboxes];emit();return cashbox}
export function assignEmployeeToBranchCashboxes(employeeId:string,branchIds:readonly string[]){let changed=false;cashboxes=cashboxes.map((cashbox)=>branchIds.includes(cashbox.branchId)&&!cashbox.assignedEmployeeIds.includes(employeeId)?(changed=true,{...cashbox,assignedEmployeeIds:[...cashbox.assignedEmployeeIds,employeeId],updatedAt:new Date().toISOString()}):cashbox);if(changed)emit();return changed}
function audit(type:string,entityType:FinanceSnapshot["audits"][number]["entityType"],entityId:string,actorEmployeeId:string,reason:string){audits=[{id:`finance-audit-${sequence++}`,type,entityType,entityId,actorEmployeeId,reason,createdAt:NOW},...audits]}
function moveBalance(cashboxId:string,direction:"incoming"|"outgoing",amount:number):{valid:true;message:string}|{valid:false;message:string}{const cashbox=cashboxes.find((item)=>item.id===cashboxId);if(!cashbox)return{valid:false,message:"الخزينة غير موجودة."};const next=cashbox.currentBalance+(direction==="incoming"?amount:-amount);if(next<0&&!cashbox.allowNegativeBalance)return{valid:false,message:"الرصيد غير كافٍ ولا تسمح الخزينة برصيد سالب."};cashboxes=cashboxes.map((item)=>item.id===cashboxId?{...item,currentBalance:next,updatedAt:NOW}:item);return{valid:true,message:"تم تحديث الرصيد بحركة موثقة."}}
export function recordPayment(input:RecordPaymentInput){const existing=payments.find((item)=>item.idempotencyKey===input.idempotencyKey);if(existing)return{valid:true,message:"تم استخدام الدفع المسجل سابقًا.",payment:existing,duplicate:true};const validation=validatePayment(input);if(!validation.valid)return validation;const admin=isFinanceAdmin(input.roles as never);if(input.roles.includes("maintenance_technician"))return{valid:false,message:"فني الصيانة لا يحصل أموالًا."};if(!input.assignedBranchIds.includes(input.branchId)&&!admin)return{valid:false,message:"لا يمكن التحصيل في فرع غير مسند."};const cashbox=cashboxes.find((item)=>item.id===input.cashboxId);if(!cashbox||cashbox.branchId!==input.branchId||cashbox.status!=="active")return{valid:false,message:"الخزينة غير متاحة للتحصيل."};if(!admin){if(!input.shiftId)return{valid:false,message:"يلزم وجود وردية مالية مفتوحة."};const shift=getOpenShift(input.employeeId,input.cashboxId);if(!shift||shift.id!==input.shiftId||shift.branchId!==input.branchId)return{valid:false,message:"الوردية المفتوحة لا تطابق الموظف والخزينة والفرع."}}else if(!input.shiftId&&!input.administrativeReason?.trim())return{valid:false,message:"سبب التحصيل الإداري خارج الوردية إلزامي."};const balance=moveBalance(input.cashboxId,"incoming",input.amount);if(!balance.valid)return balance;const id=`finance-payment-${sequence++}`;const method=input.parts.length>1?"mixed":input.parts[0].method;const payment:Payment={id,paymentNumber:`PAY-2026-${String(sequence).padStart(6,"0")}`,branchId:input.branchId,cashboxId:input.cashboxId,shiftId:input.shiftId,customerId:input.customerId,sourceType:input.sourceType,sourceId:input.sourceId,direction:"incoming",method,parts:input.parts.map((part,index)=>({id:`payment-part-${sequence}-${index}`,...part})),amount:input.amount,currency:"EGP",reference:input.sourceId,receivedByEmployeeId:input.employeeId,status:"completed",paidAt:NOW,reversedPaymentId:null,idempotencyKey:input.idempotencyKey,administrativeReason:input.administrativeReason??"",createdAt:NOW};payments=[payment,...payments];if(input.sourceType==="receivable")applyReceivablePayment(input.sourceId,input.amount,payment.id);audit("payment_recorded","payment",id,input.employeeId,input.administrativeReason||`تحصيل ${input.sourceType}`);emit();return{valid:true,message:"تم تسجيل التحصيل.",payment,duplicate:false}}
export function applyReceivablePayment(receivableId:string,amount:number,reference:string){const receivable=receivables.find((item)=>item.id===receivableId);if(!receivable||amount<=0||amount>receivable.remainingAmount)return{valid:false,message:"قيمة سداد المديونية غير صحيحة."};receivables=receivables.map((item)=>item.id===receivableId?{...item,paidAmount:item.paidAmount+amount,remainingAmount:item.remainingAmount-amount,status:item.remainingAmount-amount<=.01?"paid":"partially_paid",lastPaymentAt:NOW,updatedAt:NOW}:item);audit("receivable_payment","receivable",receivableId,"system",reference);return{valid:true,message:"تم تحديث المديونية."}}
export function reversePayment(id:string,actor:string,reason:string){
  const original=payments.find((item)=>item.id===id);
  if(!original||original.status!=="completed"||original.reversedPaymentId)return{valid:false,message:"الحركة غير قابلة للعكس أو عُكست سابقًا."};
  if(reason.trim().length<5)return{valid:false,message:"سبب العكس إلزامي."};
  const direction=original.direction==="incoming"?"outgoing":"incoming";
  const balance=moveBalance(original.cashboxId,direction,original.amount);
  if(!balance.valid)return balance;
  const reverseId=`finance-payment-${sequence++}`;
  const reversal:Payment={...clonePayment(original),id:reverseId,paymentNumber:`PAY-2026-${String(sequence).padStart(6,"0")}`,sourceType:"refund",sourceId:original.id,direction,status:"completed",paidAt:NOW,reversedPaymentId:original.id,idempotencyKey:`reverse-${original.id}`,administrativeReason:reason,createdAt:NOW};
  payments=[reversal,...payments.map((item):Payment=>item.id===id?{...item,status:"reversed",reversedPaymentId:reverseId}:item)];
  notifications=[{id:`fin-note-${sequence++}`,type:"payment_reversed",title:`عكس الحركة ${original.paymentNumber}`,href:"/finance/payments",createdAt:NOW,read:false},...notifications];
  audit("payment_reversed","payment",id,actor,reason);emit();
  return{valid:true,message:"أُنشئت حركة عكسية دون تعديل أو حذف الأصل.",payment:reversal}
}
export function recordOutgoingPayment(input:{branchId:string;cashboxId:string;sourceType:"expense"|"payroll"|"advance";sourceId:string;amount:number;employeeId:string;actorEmployeeId:string;reason:string;idempotencyKey:string}):{valid:true;message:string;payment:Payment;duplicate:boolean}|{valid:false;message:string}{
  const existing=payments.find((item)=>item.idempotencyKey===input.idempotencyKey);
  if(existing)return{valid:true,message:"تم استخدام حركة الصرف السابقة.",payment:existing,duplicate:true};
  if(input.amount<=0||input.reason.trim().length<5)return{valid:false,message:"المبلغ وسبب الصرف إلزاميان."};
  const cashbox=cashboxes.find((item)=>item.id===input.cashboxId);
  if(!cashbox||cashbox.branchId!==input.branchId||cashbox.status!=="active")return{valid:false,message:"الخزينة غير متاحة للصرف."};
  const balance=moveBalance(input.cashboxId,"outgoing",input.amount);if(!balance.valid)return balance;
  const id=`finance-payment-${sequence++}`;
  const payment:Payment={id,paymentNumber:`PAY-2026-${String(sequence).padStart(6,"0")}`,branchId:input.branchId,cashboxId:input.cashboxId,shiftId:null,customerId:null,sourceType:input.sourceType,sourceId:input.sourceId,direction:"outgoing",method:"cash",parts:[{id:`payment-part-${sequence}-0`,method:"cash",amount:input.amount,reference:input.sourceId}],amount:input.amount,currency:"EGP",reference:input.sourceId,receivedByEmployeeId:input.employeeId,status:"completed",paidAt:NOW,reversedPaymentId:null,idempotencyKey:input.idempotencyKey,administrativeReason:input.reason,createdAt:NOW};
  payments=[payment,...payments];audit("outgoing_payment_recorded","payment",id,input.actorEmployeeId,input.reason);emit();return{valid:true,message:"تم تسجيل حركة الصرف.",payment,duplicate:false};
}
export function createVoucher(input:{type:VoucherType;branchId:string;cashboxId:string;destinationCashboxId?:string;customerId?:string;employeeId?:string;amount:number;reason:string;createdBy:string;idempotencyKey:string}){const existing=vouchers.find((item)=>item.idempotencyKey===input.idempotencyKey);if(existing)return{valid:true,message:"تم استخدام السند السابق.",voucher:existing,duplicate:true};if(input.amount<=0||input.reason.trim().length<5)return{valid:false,message:"قيمة السند وسببه إلزاميان."};if(input.type==="transfer"){if(!input.destinationCashboxId||input.destinationCashboxId===input.cashboxId)return{valid:false,message:"اختر خزينة وجهة مختلفة."};const out=moveBalance(input.cashboxId,"outgoing",input.amount);if(!out.valid)return out;const incoming=moveBalance(input.destinationCashboxId,"incoming",input.amount);if(!incoming.valid){moveBalance(input.cashboxId,"incoming",input.amount);return incoming}}else{const movement=moveBalance(input.cashboxId,input.type==="receipt"?"incoming":"outgoing",input.amount);if(!movement.valid)return movement}const id=`voucher-${sequence++}`;const voucher:Voucher={id,voucherNumber:`BR-${input.type==="receipt"?"RCV":input.type==="payment"?"PAY":"TRF"}-${String(sequence).padStart(6,"0")}`,type:input.type,branchId:input.branchId,cashboxId:input.cashboxId,destinationCashboxId:input.destinationCashboxId??null,customerId:input.customerId??null,employeeId:input.employeeId??null,amount:input.amount,reason:input.reason,referenceType:input.type==="transfer"?"cashbox_transfer":"administrative",referenceId:id,status:"completed",createdBy:input.createdBy,approvedBy:input.createdBy,createdAt:NOW,approvedAt:NOW,reversedAt:null,reversalReason:"",idempotencyKey:input.idempotencyKey};vouchers=[voucher,...vouchers];audit("voucher_created","voucher",id,input.createdBy,input.reason);emit();return{valid:true,message:"تم إنشاء السند بحركة موثقة.",voucher,duplicate:false}}
export function setCashboxStatus(id:string,status:Cashbox["status"],actor:string,reason:string){if(!reason.trim())return{valid:false,message:"سبب تغيير حالة الخزينة إلزامي."};const cashbox=cashboxes.find((item)=>item.id===id);if(!cashbox)return{valid:false,message:"الخزينة غير موجودة."};cashboxes=cashboxes.map((item)=>item.id===id?{...item,status,updatedAt:NOW}:item);audit("cashbox_status","cashbox",id,actor,reason);emit();return{valid:true,message:"تم تحديث حالة الخزينة دون حذفها."}}
export function resetFinanceStore(){cashboxes=CASHBOX_FIXTURES.map((item)=>({...item,assignedEmployeeIds:[...item.assignedEmployeeIds]}));payments=PAYMENT_FIXTURES.map(clonePayment);vouchers=VOUCHER_FIXTURES.map((item)=>({...item}));receivables=RECEIVABLE_FIXTURES.map((item)=>({...item}));audits=[];notifications=FINANCE_NOTIFICATION_FIXTURES.map((item)=>({...item}));sequence=200;removeLocalTestData(STORAGE_KEY);snapshot={cashboxes,payments,vouchers,receivables,audits,notifications};listeners.forEach((listener)=>listener())}
