"use client";

import { useSearchParams } from "next/navigation";
import { useState } from "react";
import { FileClock, SlidersHorizontal } from "lucide-react";
import { PermissionDeniedState } from "@/components/feedback/PermissionDeniedState";
import { useShell } from "@/components/shell/ShellContext";
import { Card } from "@/components/ui/Card";
import { EMPLOYEE_FIXTURES } from "@/features/employees/fixtures";
import { useAudit } from "../hooks/use-audit";
import { canViewAdministrativeAudit } from "../permissions";
import type { AuditCategory, AuditEvent, AuditSeverity } from "../types";
import { ActivityDetailsDrawer } from "./ActivityDetailsDrawer";
import { auditActionLabel, auditCategoryLabels, auditRolesLabel, AuditSeverityBadge, formatAuditTime } from "./audit-ui";

function updateFilter(name: string, value: string) { const params = new URLSearchParams(window.location.search); if (value === "all") params.delete(name); else params.set(name, value); window.history.pushState(null, "", `${window.location.pathname}?${params}`); }
export function ActivityLogPage() {
  const { roles } = useShell(); const { events } = useAudit(); const params = useSearchParams(); const [selected, setSelected] = useState<AuditEvent | null>(null);
  if (!canViewAdministrativeAudit(roles)) return <PermissionDeniedState />;
  const branch = params.get("branch") ?? "all", employee = params.get("employee") ?? "all", role = params.get("role") ?? "all", category = (params.get("category") ?? "all") as AuditCategory | "all", action = params.get("action") ?? "all", entity = params.get("entity") ?? "all", severity = (params.get("severity") ?? "all") as AuditSeverity | "all", reference = params.get("reference") ?? "", period = params.get("period") ?? "all";
  const filtered = events.filter((event) => (branch === "all" || event.branchId === branch) && (employee === "all" || event.actorEmployeeId === employee) && (role === "all" || event.actorRolesSnapshot.includes(role as never)) && (category === "all" || event.category === category) && (action === "all" || event.action === action) && (entity === "all" || event.entityType === entity) && (severity === "all" || event.severity === severity) && (!reference || event.referenceNumber.toLowerCase().includes(reference.toLowerCase())) && (period === "all" || event.createdAt.startsWith("2026-08-08")));
  return <div className="activity-log-page"><header className="activity-log-header"><div><span>الإدارة</span><h2>سجل النشاط</h2><p>سجل مركزي للإضافة فقط؛ لا توجد إجراءات تعديل أو حذف.</p></div></header><section className="activity-summary"><Card><span>إجمالي الأحداث</span><strong>{events.length.toLocaleString("ar-EG-u-nu-latn")}</strong></Card><Card><span>أحداث حساسة</span><strong>{events.filter((event) => event.severity === "critical").length.toLocaleString("ar-EG-u-nu-latn")}</strong></Card><Card><span>أحداث مالية</span><strong>{events.filter((event) => ["finance", "shift", "expense", "payroll"].includes(event.category)).length.toLocaleString("ar-EG-u-nu-latn")}</strong></Card><Card><span>تغييرات صلاحيات</span><strong>{events.filter((event) => event.category === "employees").length.toLocaleString("ar-EG-u-nu-latn")}</strong></Card><Card><span>أحداث اليوم</span><strong>{events.filter((event) => event.createdAt.startsWith("2026-08-08")).length.toLocaleString("ar-EG-u-nu-latn")}</strong></Card><Card><span>مستخدمون نشطون</span><strong>{new Set(events.map((event) => event.actorEmployeeId)).size.toLocaleString("ar-EG-u-nu-latn")}</strong></Card></section>
    <Card className="activity-filters"><span><SlidersHorizontal aria-hidden size={18} />الفلاتر</span><label>الفترة<select value={period} onChange={(e) => updateFilter("period", e.target.value)}><option value="all">كل الفترات</option><option value="today">اليوم</option></select></label><label>الفرع<select value={branch} onChange={(e) => updateFilter("branch", e.target.value)}><option value="all">كل الفروع</option>{[...new Set(events.map((e) => e.branchId))].map((value) => <option key={value}>{value}</option>)}</select></label><label>الموظف<select value={employee} onChange={(e) => updateFilter("employee", e.target.value)}><option value="all">كل الموظفين</option>{EMPLOYEE_FIXTURES.filter((item) => events.some((e) => e.actorEmployeeId === item.id)).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>الدور<select value={role} onChange={(e) => updateFilter("role", e.target.value)}><option value="all">كل الأدوار</option>{["owner", "manager", "sales_employee", "rental_maintenance_employee", "maintenance_technician"].map((value) => <option key={value}>{value}</option>)}</select></label><label>القسم<select value={category} onChange={(e) => updateFilter("category", e.target.value)}><option value="all">كل الأقسام</option>{Object.entries(auditCategoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>الإجراء<select value={action} onChange={(e) => updateFilter("action", e.target.value)}><option value="all">كل الإجراءات</option>{[...new Set(events.map((e) => e.action))].map((value) => <option key={value}>{value}</option>)}</select></label><label>الكيان<select value={entity} onChange={(e) => updateFilter("entity", e.target.value)}><option value="all">كل الكيانات</option>{[...new Set(events.map((e) => e.entityType))].map((value) => <option key={value}>{value}</option>)}</select></label><label>الأهمية<select value={severity} onChange={(e) => updateFilter("severity", e.target.value)}><option value="all">كل المستويات</option><option value="critical">حساس</option><option value="important">مهم</option><option value="notice">ملحوظ</option><option value="info">معلومة</option></select></label><label>رقم المرجع<input value={reference} onChange={(e) => updateFilter("reference", e.target.value)} placeholder="AUD / RNT / SAL" /></label></Card>
    {filtered.length ? <Card className="activity-list"><div className="activity-table-wrap"><table><thead><tr><th>الوقت</th><th>المستخدم</th><th>الدور</th><th>الفرع</th><th>الإجراء</th><th>القسم</th><th>المرجع</th><th>الأهمية</th><th>التفاصيل</th></tr></thead><tbody>{filtered.map((event) => <tr key={event.id}><td>{formatAuditTime(event.createdAt)}</td><td>{event.actorEmployeeId}</td><td>{auditRolesLabel(event.actorRolesSnapshot)}</td><td>{event.branchId}</td><td>{auditActionLabel(event.action)}</td><td>{auditCategoryLabels[event.category]}</td><td>{event.referenceNumber}</td><td><AuditSeverityBadge severity={event.severity} /></td><td><button onClick={() => setSelected(event)}>عرض</button></td></tr>)}</tbody></table></div><div className="activity-mobile-list">{filtered.map((event) => <article className="activity-mobile-card" key={event.id}><header><strong>{auditActionLabel(event.action)}</strong><AuditSeverityBadge severity={event.severity} /></header><p>{event.reason}</p><dl><div><dt>المستخدم</dt><dd>{event.actorEmployeeId}</dd></div><div><dt>القسم</dt><dd>{auditCategoryLabels[event.category]}</dd></div><div><dt>المرجع</dt><dd>{event.referenceNumber}</dd></div><div><dt>الوقت</dt><dd>{formatAuditTime(event.createdAt)}</dd></div></dl><button onClick={() => setSelected(event)}>عرض التفاصيل</button></article>)}</div></Card> : <Card className="activity-empty"><FileClock aria-hidden /><h3>لا توجد أحداث مطابقة</h3><p>غيّر الفلاتر لعرض نطاق أوسع.</p></Card>}<ActivityDetailsDrawer event={selected} onOpenChange={(open) => { if (!open) setSelected(null); }} /></div>;
}
