import type { FaultReport, MaintenanceNotification, MaintenanceOrder, MaintenanceStatus, MaintenanceSubjectType, PartUsage, WorkshopTransfer } from "./types";

const now="2026-08-06T17:00:00+03:00";
const attachments=(index:number)=>[{id:`maintenance-attachment-${index}`,name:`صورة-حالة-${index}.jpg`,kind:"image" as const,mockUrl:`mock://maintenance/${index}`}];
const partUsage=(index:number,orderId:string,status:PartUsage["status"]="requested"):PartUsage=>({id:`part-usage-${index}`,maintenanceOrderId:orderId,productId:index%2?"part-battery-12v":"part-charger-12v",locationId:index%3?"main":"workshop",quantityRequested:index%4===0?20:1,quantityIssued:status==="issued"?1:0,status,issuedBy:status==="issued"?"employee-manager":null,issuedAt:status==="issued"?now:null,note:status==="unavailable"?"الكمية غير متاحة في Mock Stock":"طلب مرتبط بأمر الصيانة"});
const transfer=(index:number,orderId:string,status:WorkshopTransfer["status"]):WorkshopTransfer=>({id:`transfer-${index}`,maintenanceOrderId:orderId,fromBranchId:index%2?"main":"branch-2",toLocationId:"workshop",status,reason:"يتطلب تجهيزات الورشة المركزية",conditionBeforeDispatch:"مثبت ومغلف مع الملحقات",accessories:["بطارية","شاحن"],dispatchedBy:"employee-rental",receivedBy:["received","repair_in_progress","ready_to_return","returned_to_branch"].includes(status)?"employee-technician":null,dispatchedAt:status==="transfer_requested"?null:"2026-08-06T13:00:00+03:00",receivedAt:["received","repair_in_progress","ready_to_return","returned_to_branch"].includes(status)?"2026-08-06T14:00:00+03:00":null,returnedAt:status==="returned_to_branch"?now:null});

const scenarios:readonly {subject:MaintenanceSubjectType;status:MaintenanceStatus;branchId:string;item:string;fault:string;technician:string|null;customer:string|null;asset:string|null;priority:FaultReport["priority"];approval:MaintenanceOrder["customerApprovalStatus"];part?:PartUsage["status"];transfer?:WorkshopTransfer["status"];expected?:string}[]=[
  {subject:"internal_asset",status:"awaiting_acknowledgement",branchId:"main",item:"سكوتر كهربائي — رقم 1",fault:"توقف مفاجئ وصوت من وحدة التحكم",technician:null,customer:null,asset:"asset-scooter-01",priority:"urgent",approval:"not_required"},
  {subject:"customer_item",status:"awaiting_acknowledgement",branchId:"main",item:"عربية أطفال كهربائية حمراء",fault:"لا تعمل بعد الشحن",technician:"employee-technician",customer:"customer-001",asset:null,priority:"high",approval:"pending"},
  {subject:"internal_asset",status:"diagnosing",branchId:"branch-2",item:"هوفر بورد — رقم 1",fault:"اهتزاز وانطفاء متكرر",technician:"employee-technician",customer:null,asset:"asset-hoverboard-01",priority:"normal",approval:"not_required"},
  {subject:"customer_item",status:"awaiting_customer_approval",branchId:"main",item:"موتوسيكل أطفال كهربائي",fault:"الموتور يعمل ببطء",technician:"employee-technician",customer:"customer-002",asset:null,priority:"normal",approval:"pending"},
  {subject:"customer_item",status:"awaiting_part",branchId:"branch-2",item:"عربية دريفت زرقاء",fault:"البطارية لا تحتفظ بالشحن",technician:"employee-technician",customer:"customer-003",asset:null,priority:"high",approval:"approved",part:"unavailable"},
  {subject:"internal_asset",status:"in_repair",branchId:"main",item:"عربية أطفال كهربائية — رقم 2",fault:"عطل بدواسة التشغيل",technician:"employee-technician",customer:null,asset:"asset-kids-car-02",priority:"high",approval:"not_required",part:"issued"},
  {subject:"customer_item",status:"in_transit_to_workshop",branchId:"branch-2",item:"هوفر بورد أسود",fault:"كسر داخلي يحتاج معدات الورشة",technician:"employee-technician",customer:"customer-004",asset:null,priority:"normal",approval:"approved",transfer:"in_transit"},
  {subject:"internal_asset",status:"received_at_workshop",branchId:"main",item:"عربية سباق كهربائية",fault:"فحص دائرة التحكم",technician:"employee-technician",customer:null,asset:"asset-race-workshop",priority:"normal",approval:"not_required",transfer:"received"},
  {subject:"internal_asset",status:"ready_for_return",branchId:"main",item:"عربية دفع رباعي للأطفال",fault:"إصلاح ضفيرة الكهرباء",technician:"employee-technician",customer:null,asset:"asset-4x4-01",priority:"normal",approval:"not_required",transfer:"ready_to_return"},
  {subject:"customer_item",status:"ready_for_delivery",branchId:"main",item:"سكوتر كهربائي أحمر",fault:"استبدال الشاحن وفحص البطارية",technician:"employee-technician",customer:"customer-005",asset:null,priority:"normal",approval:"approved",part:"issued"},
  {subject:"customer_item",status:"cancelled",branchId:"branch-2",item:"عربية أطفال بيضاء",fault:"العميل رفض التقدير",technician:"employee-technician",customer:"customer-006",asset:null,priority:"low",approval:"rejected"},
  {subject:"customer_item",status:"in_repair",branchId:"main",item:"عربية دريفت حمراء",fault:"تغيير موتور الحركة",technician:"employee-technician",customer:"customer-007",asset:null,priority:"high",approval:"approved",part:"requested",expected:"2026-08-05T16:00:00+03:00"},
  {subject:"internal_asset",status:"quality_check",branchId:"branch-2",item:"موتوسيكل أطفال كهربائي — رقم 1",fault:"مراجعة الفرامل والدائرة",technician:"employee-technician",customer:null,asset:"asset-motorbike-01",priority:"normal",approval:"not_required"},
  {subject:"customer_item",status:"delivered",branchId:"main",item:"عربية أطفال كهربائية وردية",fault:"استبدال مفتاح التشغيل",technician:"employee-technician",customer:"customer-008",asset:null,priority:"normal",approval:"approved",part:"issued"},
  {subject:"internal_asset",status:"closed",branchId:"main",item:"عربية أطفال كهربائية قديمة",fault:"فحص نهائي وإيقاف الأصل",technician:"employee-technician",customer:null,asset:"asset-electric-car-retired",priority:"low",approval:"not_required"},
];

export const MAINTENANCE_FAULT_FIXTURES:readonly FaultReport[]=scenarios.map((scenario,index)=>({
  id:`fault-${index+1}`,faultNumber:`FLT-2026-${String(index+1).padStart(4,"0")}`,branchId:scenario.branchId,locationId:scenario.branchId,reportedByEmployeeId:"employee-rental",reportedAt:`2026-08-0${index%6+1}T${String(9+index%8).padStart(2,"0")}:00:00+03:00`,subjectType:scenario.subject,rentalAssetId:scenario.asset,customerId:scenario.customer,customerItemId:scenario.subject==="customer_item"?`customer-item-${index+1}`:null,itemName:scenario.item,itemDescription:scenario.subject==="customer_item"?"لعبة كهربائية مملوكة للعميل":"أصل تأجير تابع للنشاط",faultDescription:scenario.fault,intakeCondition:"تم الاستلام مع توثيق الحالة الخارجية",accessories:scenario.subject==="customer_item"?["بطارية","شاحن"]:["بطارية"],evidenceAttachments:attachments(index+1),priority:scenario.priority,currentLocation:scenario.transfer?"workshop":scenario.branchId,assignedTechnicianId:scenario.technician,notifiedAt:now,acknowledgedAt:scenario.status==="awaiting_acknowledgement"?null:now,status:scenario.status==="awaiting_acknowledgement"?(scenario.technician?"notified":"reported"):scenario.status==="cancelled"?"cancelled":scenario.status==="closed"?"closed":"converted_to_order",stoppedOperating:scenario.priority==="urgent",expectedInspectionAt:"2026-08-07T11:00:00+03:00",notes:"بيانات صيانة تجريبية حتمية",createdAt:now,updatedAt:now,
}));

export const MAINTENANCE_ORDER_FIXTURES:readonly MaintenanceOrder[]=scenarios.map((scenario,index)=>{
  const id=`maintenance-order-${index+1}`;const usage=scenario.part?partUsage(index+1,id,scenario.part):null;const workshop=scenario.transfer?transfer(index+1,id,scenario.transfer):null;
  const labour=scenario.subject==="customer_item"?450+index*20:0;const parts=usage?usage.quantityRequested*480:0;
  return{id,orderNumber:`MNT-2026-${String(index+1).padStart(4,"0")}`,faultReportId:`fault-${index+1}`,subjectType:scenario.subject,branchId:scenario.branchId,customerId:scenario.customer,rentalAssetId:scenario.asset,customerItemId:scenario.subject==="customer_item"?`customer-item-${index+1}`:null,assignedTechnicianId:scenario.technician,status:scenario.status,diagnosis:scenario.status==="awaiting_acknowledgement"?"":"تشخيص فني Mock مرتبط بالعطل",faultCause:scenario.status==="awaiting_acknowledgement"?"":"تلف أو ضعف في دائرة كهربائية",recommendedAction:scenario.status==="awaiting_acknowledgement"?"":"فحص الدائرة واستبدال الجزء عند الحاجة",labourEstimate:labour,partsEstimate:parts,estimatedTotal:labour+parts,approvedEstimate:scenario.approval==="approved"?labour+parts:0,finalLabourAmount:["delivered","closed"].includes(scenario.status)?labour:0,finalPartsAmount:["delivered","closed"].includes(scenario.status)?parts:0,finalTotal:["delivered","closed"].includes(scenario.status)?labour+parts:0,customerApprovalStatus:scenario.approval,technicianNotes:"ملاحظة فنية تجريبية",partUsages:usage?[usage]:[],workshopTransfer:workshop,labourWarrantyDays:30,partsWarrantyDays:usage?90:0,startedAt:["in_repair","quality_check","ready_for_return","ready_for_delivery","delivered","closed"].includes(scenario.status)?now:null,completedAt:["quality_check","ready_for_return","ready_for_delivery","delivered","closed"].includes(scenario.status)?now:null,readyAt:["ready_for_return","ready_for_delivery","delivered","closed"].includes(scenario.status)?now:null,deliveredAt:["delivered","closed"].includes(scenario.status)?now:null,expectedCompletionAt:scenario.expected??"2026-08-08T16:00:00+03:00",currentLocation:scenario.transfer?"workshop":scenario.branchId,events:[{id:`maintenance-event-${index+1}`,type:"fixture",at:now,by:"mock-seed",branchId:scenario.branchId,previousValue:"",newValue:scenario.status,reason:"سيناريو صيانة تجريبي"}],createdAt:now,updatedAt:now};
});

export const MAINTENANCE_NOTIFICATION_FIXTURES:readonly MaintenanceNotification[]=[
  {id:"maintenance-notification-1",recipientEmployeeId:null,recipientRole:"maintenance_technician",branchId:"main",title:"بلاغ عاجل غير مسند",message:"FLT-2026-0001 · الفرع الرئيسي · كريم رجب · سكوتر كهربائي · توقف مفاجئ",href:"/maintenance/faults/fault-1",createdAt:now,read:false},
  {id:"maintenance-notification-2",recipientEmployeeId:"employee-technician",recipientRole:"maintenance_technician",branchId:"main",title:"بلاغ مسند إليك",message:"FLT-2026-0002 · لعبة عميل · لا تعمل بعد الشحن",href:"/maintenance/faults/fault-2",createdAt:now,read:false},
  {id:"maintenance-notification-3",recipientEmployeeId:null,recipientRole:"manager",branchId:"main",title:"بلاغ يحتاج تعيين فني",message:"FLT-2026-0001 بلا فني مسؤول",href:"/maintenance/faults/fault-1",createdAt:now,read:false},
];
