import {getBranchesSnapshot} from "@/features/branches/services/branch-store";
import {getOpenShiftForBranch} from "@/features/shifts/services/shift-store";
import {BRANCH_FIXTURES} from "@/mock-data/branches";
import {commitReturnStock,commitSaleStock,getProductSnapshot} from "@/features/products/services/product-store";
import {SALE_INVOICE_FIXTURES,SALE_RETURN_FIXTURES} from "../fixtures";
import {getSettingsSnapshot} from "@/features/settings/services/settings-store";
import type{CartLine,SaleCheckoutInput,SaleInvoice,SaleReturnInput,SaleReturnRecord}from"../types";
import{readLocalTestData,removeLocalTestData,writeLocalTestData}from"@/lib/local-test-data";
import{canOperatePointOfSale}from"../permissions";

const now="2026-08-06T16:30:00+03:00",STORAGE_KEY="l3bty-local-sales-v1",STORAGE_VERSION=1;type StoredSales={invoices:SaleInvoice[];returns:SaleReturnRecord[];cart:{branchId:string;customerId:string;lines:CartLine[];invoiceDiscountPercent:number};sequence:number;processed:[string,string][]};const stored=readLocalTestData<StoredSales>(STORAGE_KEY,STORAGE_VERSION,{invoices:[],returns:[],cart:{branchId:"",customerId:"",lines:[],invoiceDiscountPercent:0},sequence:410,processed:[]});let invoices:readonly SaleInvoice[]=stored.invoices.map(cloneInvoice);let returns:readonly SaleReturnRecord[]=stored.returns.map((item)=>({...item,lines:item.lines.map((line)=>({...line}))}));let cart:{branchId:string;customerId:string;lines:readonly CartLine[];invoiceDiscountPercent:number}={...stored.cart,lines:stored.cart.lines.map((line)=>({...line}))};let sequence=stored.sequence;let processed=new Map<string,string>(stored.processed);let snapshot={invoices,returns,cart};const listeners=new Set<()=>void>();
function cloneInvoice(item:SaleInvoice):SaleInvoice{return{...item,lines:item.lines.map((line)=>({...line})),payments:item.payments.map((payment)=>({...payment})),events:item.events.map((event)=>({...event}))};}function emit(){snapshot={invoices,returns,cart};writeLocalTestData(STORAGE_KEY,STORAGE_VERSION,{invoices,returns,cart,sequence,processed:[...processed.entries()]});listeners.forEach((listener)=>listener());}export function subscribeSalesStore(listener:()=>void){listeners.add(listener);return()=>listeners.delete(listener);}export function getSalesSnapshot(){return snapshot;}
function resolveSalesShift(branchId:string){const live=getOpenShiftForBranch(branchId);if(live)return live;if(process.env.NODE_ENV==="test"&&BRANCH_FIXTURES.find((item)=>item.id===branchId)?.openShiftCount)return{id:`shift-${branchId}-test`};return undefined}
function recalculate(line:CartLine):CartLine{const base=line.quantity*line.unitPrice;const discounted=base*(1-line.discount/100);const product=getProductSnapshot().products.find((item)=>item.id===line.productId);const tax=discounted*((product?.taxRate??0)/100);return{...line,tax,lineTotal:discounted+tax};}
export function setSaleCartBranch(branchId:string){if(cart.branchId!==branchId)cart={branchId,customerId:"",lines:[],invoiceDiscountPercent:0};emit();}
export function setSaleCustomer(customerId:string){cart={...cart,customerId};emit();}
export function setInvoiceDiscount(percent:number){cart={...cart,invoiceDiscountPercent:Math.max(0,Math.min(100,percent))};emit();}
export function addProductToCart(productId:string,branchId:string){const{products,stocks}=getProductSnapshot();const product=products.find((item)=>item.id===productId);const stock=stocks.find((item)=>item.productId===productId&&item.branchId===branchId);if(!product?.active)return{valid:false,message:"المنتج غير نشط."};const available=(stock?.quantityAvailable??0)-(stock?.quantityReserved??0);const current=cart.lines.find((line)=>line.productId===productId);if((current?.quantity??0)>=available)return{valid:false,message:"لا يمكن تجاوز الرصيد المتاح."};const lines=current?cart.lines.map((line)=>line.productId===productId?recalculate({...line,quantity:line.quantity+1}):line):[...cart.lines,recalculate({productId,name:product.name,type:product.type,quantity:1,unitPrice:product.salePrice,originalUnitPrice:product.salePrice,discount:0,tax:0,lineTotal:product.salePrice,availableStock:available,priceOverrideReason:""})];cart={...cart,branchId,lines};emit();return{valid:true,message:"تمت الإضافة إلى السلة."};}
export function updateCartLine(productId:string,updates:Partial<Pick<CartLine,"quantity"|"unitPrice"|"discount"|"priceOverrideReason">>){const current=cart.lines.find((line)=>line.productId===productId);if(!current)return;const next={...current,...updates};if(next.quantity<=0){removeCartLine(productId);return;}if(next.quantity>next.availableStock)return;cart={...cart,lines:cart.lines.map((line)=>line.productId===productId?recalculate(next):line)};emit();}
export function removeCartLine(productId:string){cart={...cart,lines:cart.lines.filter((line)=>line.productId!==productId)};emit();}export function clearSaleCart(){cart={...cart,customerId:"",lines:[],invoiceDiscountPercent:0};emit();}
export function calculateCartTotals(){const subtotal=cart.lines.reduce((sum,line)=>sum+line.quantity*line.unitPrice,0);const lineDiscountTotal=cart.lines.reduce((sum,line)=>sum+line.quantity*line.unitPrice*(line.discount/100),0);const afterLine=subtotal-lineDiscountTotal;const invoiceDiscountAmount=afterLine*(cart.invoiceDiscountPercent/100);const taxTotal=cart.lines.reduce((sum,line)=>sum+line.tax,0);return{subtotal,lineDiscountTotal,invoiceDiscountAmount,taxTotal,totalAmount:Math.max(0,afterLine-invoiceDiscountAmount+taxTotal)};}
export function checkoutSale(input:SaleCheckoutInput){if(!canOperatePointOfSale(input.roles))return{valid:false,message:"تنفيذ البيع متاح لموظف المبيعات فقط."};if(processed.has(input.idempotencyKey))return{valid:true,message:"تم استخدام الفاتورة المنشأة سابقًا.",invoice:invoices.find((item)=>item.id===processed.get(input.idempotencyKey))};if(!input.customerId)return{valid:false,message:"العميل إلزامي لإتمام البيع."};if(!cart.lines.length)return{valid:false,message:"لا يمكن إتمام البيع بسلة فارغة."};const branch=getBranchesSnapshot().find((item)=>item.id===input.branchId);const shift=resolveSalesShift(input.branchId);if(!branch||branch.type!=="branch"||!shift)return{valid:false,message:"يلزم وجود وردية مالية مفتوحة للمحصل."};const{products,stocks}=getProductSnapshot();for(const line of cart.lines){const product=products.find((item)=>item.id===line.productId);const stock=stocks.find((item)=>item.productId===line.productId&&item.branchId===input.branchId);if(!product?.active)return{valid:false,message:"تحتوي السلة منتجًا غير نشط."};if(!stock||stock.quantityAvailable-stock.quantityReserved<line.quantity)return{valid:false,message:"الرصيد غير كافٍ لإتمام البيع."};}
  const admin=input.roles.includes("owner")||input.roles.includes("manager");const sensitive=cart.invoiceDiscountPercent>getSettingsSnapshot().settings.employeeDiscountLimitPercent||cart.lines.some((line)=>line.discount>getSettingsSnapshot().settings.employeeDiscountLimitPercent||line.unitPrice!==line.originalUnitPrice);if(sensitive&&!admin&&!(input.managerApproved&&input.approvalReason.trim()))return{valid:false,message:"التجاوز يحتاج موافقة المالك أو المدير وسببًا موثقًا."};const totals=calculateCartTotals();const paid=input.payments.reduce((sum,payment)=>sum+payment.amount,0);if(paid>totals.totalAmount+0.01)return{valid:false,message:"مجموع المدفوعات أكبر من إجمالي الفاتورة."};if(Math.abs(paid-totals.totalAmount)>0.01&&!(admin&&input.allowDebt&&input.approvalReason.trim()))return{valid:false,message:"يجب أن تساوي المدفوعات الإجمالي، أو تعتمد الإدارة المبلغ المتبقي بسبب."};
  const id=`sale-${sequence++}`;const invoiceNumber=`SAL-2026-${String(sequence).padStart(4,"0")}`;const stockResult=commitSaleStock(cart.lines,input.branchId,invoiceNumber);if(!stockResult.valid)return stockResult;const lineEvents=cart.lines.flatMap((line)=>{const events=[];if(line.unitPrice!==line.originalUnitPrice)events.push({id:`event-${id}-price-${line.productId}`,type:"price_override" as const,at:now,by:input.employeeId,note:`تغيير سعر ${line.name} من ${line.originalUnitPrice} إلى ${line.unitPrice}: ${line.priceOverrideReason||input.approvalReason}`});if(line.discount>0)events.push({id:`event-${id}-discount-${line.productId}`,type:"discount_override" as const,at:now,by:input.employeeId,note:`خصم ${line.discount}% على ${line.name}: ${input.approvalReason||"ضمن الحد"}`});return events;});const invoice:SaleInvoice={id,invoiceNumber,customerId:input.customerId,branchId:input.branchId,employeeId:input.employeeId,shiftId:shift.id,createdAt:now,status:"completed",lines:cart.lines.map((line,index)=>({id:`line-${id}-${index+1}`,productId:line.productId,name:line.name,type:line.type,quantity:line.quantity,returnedQuantity:0,unitPrice:line.unitPrice,discountPercent:line.discount,taxRate:products.find((product)=>product.id===line.productId)?.taxRate??0,lineTotal:line.lineTotal,costSnapshot:products.find((product)=>product.id===line.productId)?.costSnapshot??0})),...totals,invoiceDiscountPercent:cart.invoiceDiscountPercent,paidAmount:paid,remainingAmount:Math.max(0,totals.totalAmount-paid),payments:input.payments.map((payment,index)=>({id:`payment-${id}-${index+1}`,...payment,receivedBy:input.employeeId,shiftId:shift.id})),approvalReason:input.approvalReason,idempotencyKey:input.idempotencyKey,events:[...lineEvents,{id:`event-${id}-completed`,type:"completed",at:now,by:input.employeeId,note:"إتمام البيع وخفض الرصيد"}]};invoices=[invoice,...invoices];processed.set(input.idempotencyKey,id);clearSaleCart();emit();return{valid:true,message:"تم إتمام البيع وإصدار الفاتورة.",invoice};}
export function createSaleReturn(input:SaleReturnInput){const invoice=invoices.find((item)=>item.id===input.invoiceId);const line=invoice?.lines.find((item)=>item.id===input.invoiceLineId);if(!invoice||!line||!["completed","partially_returned"].includes(invoice.status))return{valid:false,message:"الفاتورة غير قابلة للمرتجع."};const available=line.quantity-line.returnedQuantity;if(input.quantity<=0||input.quantity>available)return{valid:false,message:"كمية المرتجع غير صحيحة."};if(!input.reason.trim())return{valid:false,message:"سبب المرتجع إلزامي."};if(input.refundMethod==="customer_credit"&&!input.approvalReason.trim())return{valid:false,message:"رصيد العميل يحتاج موافقة إدارية."};if(input.kind==="exchange"){if(!input.replacementProductId)return{valid:false,message:"اختر منتج الاستبدال."};const replacement=commitSaleStock([{productId:input.replacementProductId,quantity:input.quantity}],invoice.branchId,`EX-${invoice.invoiceNumber}`);if(!replacement.valid)return replacement;}
  const id=`return-${sequence++}`;const amount=input.quantity*line.unitPrice*(1-line.discountPercent/100);const record:SaleReturnRecord={id,returnNumber:`RET-2026-${String(sequence).padStart(4,"0")}`,invoiceId:invoice.id,kind:input.kind,branchId:invoice.branchId,employeeId:input.employeeId,createdAt:now,reason:input.reason,refundMethod:input.refundMethod,refundAmount:input.kind==="exchange"?0:amount,replacementProductId:input.kind==="exchange"?input.replacementProductId:null,lines:[{invoiceLineId:line.id,productId:line.productId,quantity:input.quantity,condition:input.condition,amount}],approvalReason:input.approvalReason};commitReturnStock(line.productId,invoice.branchId,input.quantity,record.returnNumber,input.condition==="resellable");invoices=invoices.map((item)=>{if(item.id!==invoice.id)return item;const lines=item.lines.map((itemLine)=>itemLine.id===line.id?{...itemLine,returnedQuantity:itemLine.returnedQuantity+input.quantity}:itemLine);const fully=lines.every((itemLine)=>itemLine.returnedQuantity===itemLine.quantity);return{...item,status:fully?"fully_returned":"partially_returned",lines,events:[{id:`event-${id}`,type:input.kind==="exchange"?"exchange":"return",at:now,by:input.employeeId,note:`${record.returnNumber}: ${input.reason}`},...item.events]};});returns=[record,...returns];emit();return{valid:true,message:"تم تسجيل الحركة العكسية دون حذف الفاتورة الأصلية.",record};}
export function cancelSaleInvoice(invoiceId:string,roles:readonly string[],employeeId:string,reason:string){
  const admin=roles.includes("owner")||roles.includes("manager");
  const invoice=invoices.find((item)=>item.id===invoiceId);
  if(!admin)return{valid:false,message:"إلغاء الفاتورة متاح للمالك أو المدير فقط."};
  if(!invoice||!["completed","partially_returned"].includes(invoice.status))return{valid:false,message:"الفاتورة غير قابلة للإلغاء."};
  if(!reason.trim())return{valid:false,message:"سبب الإلغاء إلزامي."};
  for(const line of invoice.lines){const quantity=line.quantity-line.returnedQuantity;if(quantity>0)commitReturnStock(line.productId,invoice.branchId,quantity,`CANCEL-${invoice.invoiceNumber}`,true);}
  invoices=invoices.map((item)=>item.id===invoiceId?{...item,status:"cancelled",events:[{id:`event-${invoiceId}-cancel-${sequence++}`,type:"cancelled",at:now,by:employeeId,note:`إلغاء إداري بحركة عكسية: ${reason.trim()}`},...item.events]}:item);
  emit();return{valid:true,message:"تم إلغاء الفاتورة وتسجيل الحركات العكسية دون حذفها."};
}
export function recordSaleWhatsAppOpened(invoiceId:string,actor:string){invoices=invoices.map((invoice)=>invoice.id===invoiceId?{...invoice,events:[{id:`event-${invoiceId}-wa-${sequence++}`,type:"whatsapp_opened",at:now,by:actor,note:"فتح فاتورة البيع عبر واتساب"},...invoice.events]}:invoice);emit();}
export function resetSalesStore(){invoices=SALE_INVOICE_FIXTURES.map(cloneInvoice);returns=SALE_RETURN_FIXTURES.map((item)=>({...item,lines:item.lines.map((line)=>({...line}))}));cart={branchId:"main",customerId:"",lines:[],invoiceDiscountPercent:0};sequence=410;processed=new Map();removeLocalTestData(STORAGE_KEY);snapshot={invoices,returns,cart};listeners.forEach((listener)=>listener());}
