"use client";
import {useState}from"react";
import{Button}from"@/components/ui/Button";
import type{Branch}from"@/features/branches/types";
import type{ProductFormValues,SaleProduct}from"../types";
import{saveProduct}from"../services/product-store";

export function ProductForm({product,branches,onSaved,onCancel,offline=false}:{product?:SaleProduct;branches:readonly Branch[];onSaved:()=>void;onCancel:()=>void;offline?:boolean}){
 const [notice,setNotice]=useState("");const [values,setValues]=useState<ProductFormValues>({name:product?.name??"",type:product?.type??"sale_toy",sku:product?.sku??"",barcode:product?.barcode??"",category:product?.category??"",brand:product?.brand??"",description:product?.description??"",salePrice:product?.salePrice??0,costSnapshot:product?.costSnapshot??0,taxRate:product?.taxRate??0,warrantyDays:product?.warrantyDays??0,active:product?.active??true,imageMockKey:product?.imageMockKey??"",openingStock:Object.fromEntries(branches.filter((branch)=>branch.type==="branch").map((branch)=>[branch.id,0])),minimumStock:1});
 function set<K extends keyof ProductFormValues>(key:K,value:ProductFormValues[K]){setValues((current)=>({...current,[key]:value}));}
 function submit(){if(offline){setNotice("التعديل معطل دون اتصال، ولا توجد Offline Queue.");return;}const result=saveProduct(values,product?.id);setNotice(result.message);if(result.valid)onSaved();}
 return <form className="product-form" onSubmit={(event)=>{event.preventDefault();submit();}}><div className="product-form__grid"><label><span>اسم المنتج *</span><input value={values.name} onChange={(event)=>set("name",event.target.value)}/></label><label><span>النوع *</span><select value={values.type} onChange={(event)=>set("type",event.target.value as ProductFormValues["type"])}><option value="sale_toy">لعبة للبيع</option><option value="spare_part">قطعة غيار</option></select></label><label><span>SKU *</span><input dir="ltr" value={values.sku} onChange={(event)=>set("sku",event.target.value)}/></label><label><span>Barcode</span><input dir="ltr" value={values.barcode} onChange={(event)=>set("barcode",event.target.value)}/></label><label><span>الفئة</span><input value={values.category} onChange={(event)=>set("category",event.target.value)}/></label><label><span>العلامة</span><input value={values.brand} onChange={(event)=>set("brand",event.target.value)}/></label><label><span>سعر البيع</span><input type="number" min="0" value={values.salePrice} onChange={(event)=>set("salePrice",Number(event.target.value))}/></label><label><span>التكلفة التجريبية</span><input type="number" min="0" value={values.costSnapshot} onChange={(event)=>set("costSnapshot",Number(event.target.value))}/></label><label><span>الضريبة %</span><input type="number" min="0" value={values.taxRate} onChange={(event)=>set("taxRate",Number(event.target.value))}/></label><label><span>الضمان بالأيام</span><input type="number" min="0" value={values.warrantyDays} onChange={(event)=>set("warrantyDays",Number(event.target.value))}/></label><label><span>صورة Mock اختيارية</span><input value={values.imageMockKey} onChange={(event)=>set("imageMockKey",event.target.value)}/></label><label><span>الحد الأدنى للمخزون</span><input type="number" min="0" value={values.minimumStock} onChange={(event)=>set("minimumStock",Number(event.target.value))}/></label></div><label><span>الوصف</span><textarea rows={3} value={values.description} onChange={(event)=>set("description",event.target.value)}/></label>{!product?<fieldset><legend>الرصيد الافتتاحي Mock لكل فرع</legend>{branches.filter((branch)=>branch.type==="branch").map((branch)=><label key={branch.id}><span>{branch.name}</span><input type="number" min="0" value={values.openingStock[branch.id]??0} onChange={(event)=>set("openingStock",{...values.openingStock,[branch.id]:Number(event.target.value)})}/></label>)}</fieldset>:null}<label className="product-form__check"><input type="checkbox" checked={values.active} onChange={(event)=>set("active",event.target.checked)}/><span>منتج نشط</span></label>{notice?<p role="alert">{notice}</p>:null}<div className="product-form__actions"><Button type="button" variant="ghost" onClick={onCancel}>إلغاء</Button><Button type="submit" variant="primary" disabled={offline}>حفظ المنتج</Button></div></form>;
}
