import { Drawer } from "@/components/ui/Drawer";
import type { BranchOption } from "@/features/branches/types";
import { ROLE_TEMPLATES } from "@/permissions/role-templates";
import { ROLE_IDS } from "@/permissions/types";
import { employeeStatusLabels, employmentTypeLabels } from "./employee-labels";
import type { EmployeeFilters } from "../types";

export function EmployeesFilters({ open, onOpenChange, branches, filters, onChange }: { open: boolean; onOpenChange: (open: boolean) => void; branches: readonly BranchOption[]; filters: EmployeeFilters; onChange: (key: keyof EmployeeFilters, value: string) => void }) { return <Drawer open={open} onOpenChange={onOpenChange} title="تصفية الموظفين" description="تضييق النتائج حسب الفرع والدور والحالة." variant="auxiliary"><div className="employees-filter-form"><Filter label="الفرع" value={filters.branch} onChange={(value) => onChange("branch", value)} options={[["all", "كل الفروع"], ...branches.filter((branch) => branch.id !== "all").map((branch) => [branch.id, branch.nameAr])]} /><Filter label="الدور" value={filters.role} onChange={(value) => onChange("role", value)} options={[["all", "كل الأدوار"], ...ROLE_IDS.map((role) => [role, ROLE_TEMPLATES[role].labelAr])]} /><Filter label="الحالة" value={filters.status} onChange={(value) => onChange("status", value)} options={[["all", "كل الحالات"], ...Object.entries(employeeStatusLabels)]} /><Filter label="نوع التوظيف" value={filters.employmentType} onChange={(value) => onChange("employmentType", value)} options={[["all", "كل الأنواع"], ...Object.entries(employmentTypeLabels)]} /><Filter label="تعدد الأدوار" value={filters.multiRole} onChange={(value) => onChange("multiRole", value)} options={[["all", "الكل"], ["yes", "متعدد الأدوار"], ["no", "دور واحد"]]} /><Filter label="الترتيب" value={filters.sort} onChange={(value) => onChange("sort", value)} options={[["recent", "آخر نشاط"], ["name", "الاسم"], ["employee_number", "رقم الموظف"]]} /></div></Drawer>; }
function Filter({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <label className="employee-field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([option, text]) => <option value={option} key={option}>{text}</option>)}</select></label>; }
