import type { Expense, ExpenseCategory } from "./types";

export const EXPENSE_CATEGORY_FIXTURES:readonly ExpenseCategory[]=[
  {id:"exp-cat-shipping",name:"نقل وشحن",active:true,requiresApproval:true,approvalLimit:"1000.00",allowedRoles:["owner","manager","sales_employee","rental_maintenance_employee","maintenance_technician"],branchScoped:true},
  {id:"exp-cat-equipment",name:"صيانة معدات",active:true,requiresApproval:true,approvalLimit:"2000.00",allowedRoles:["owner","manager","rental_maintenance_employee","maintenance_technician"],branchScoped:true,requiresAttachment:true},
  {id:"exp-cat-tools",name:"شراء أدوات",active:true,requiresApproval:true,approvalLimit:"1500.00",allowedRoles:["owner","manager","rental_maintenance_employee","maintenance_technician"],branchScoped:true},
  {id:"exp-cat-utilities",name:"كهرباء ومرافق",active:true,requiresApproval:true,approvalLimit:"3000.00",allowedRoles:["owner","manager"],branchScoped:true,requiresAttachment:true},
  {id:"exp-cat-cleaning",name:"نظافة",active:true,requiresApproval:true,approvalLimit:"800.00",allowedRoles:["owner","manager","rental_maintenance_employee"],branchScoped:true},
  {id:"exp-cat-hospitality",name:"ضيافة إدارية",active:true,requiresApproval:true,approvalLimit:"600.00",allowedRoles:["owner","manager"],branchScoped:false},
  {id:"exp-cat-emergency",name:"مصروف طارئ",active:true,requiresApproval:true,approvalLimit:"500.00",allowedRoles:["owner","manager","sales_employee","rental_maintenance_employee","maintenance_technician"],branchScoped:true},
  {id:"exp-cat-custody",name:"عهدة موظف",active:true,requiresApproval:true,approvalLimit:"1000.00",allowedRoles:["owner","manager","sales_employee","rental_maintenance_employee","maintenance_technician"],branchScoped:true},
  {id:"exp-cat-operations",name:"مشتريات تشغيلية",active:true,requiresApproval:true,approvalLimit:"1200.00",allowedRoles:["owner","manager","sales_employee","rental_maintenance_employee","maintenance_technician"],branchScoped:true},
];
const base=(value:Partial<Expense>&Pick<Expense,"id"|"expenseNumber"|"branchId"|"categoryId"|"categoryName"|"requestedByEmployeeId"|"amount"|"status"|"approvalStatus"|"paidStatus">):Expense=>({approvedByEmployeeId:null,cashboxId:null,currency:"EGP",expenseDate:"2026-08-06",description:"مصروف تشغيلي تجريبي",businessPurpose:"دعم مهمة تشغيلية موثقة",attachments:[],paymentId:null,rejectionReason:"",cancellationReason:"",paidPersonally:false,reimbursementRequested:false,createdAt:"2026-08-06T10:00:00+03:00",updatedAt:"2026-08-06T10:00:00+03:00",approvedAt:null,paidAt:null,...value});
export const EXPENSE_FIXTURES:readonly Expense[]=[
  base({id:"expense-new",expenseNumber:"EXP-2026-0001",branchId:"branch-2",categoryId:"exp-cat-shipping",categoryName:"نقل وشحن",requestedByEmployeeId:"employee-sales",amount:"240.00",status:"submitted",approvalStatus:"pending",paidStatus:"unpaid"}),
  base({id:"expense-pending",expenseNumber:"EXP-2026-0002",branchId:"main",categoryId:"exp-cat-tools",categoryName:"شراء أدوات",requestedByEmployeeId:"employee-rental",amount:"1350.00",status:"pending_approval",approvalStatus:"pending",paidStatus:"unpaid",attachments:[{id:"att-2",name:"فاتورة أدوات Mock",mockReference:"mock://expense/2"}]}),
  base({id:"expense-approved",expenseNumber:"EXP-2026-0003",branchId:"workshop",categoryId:"exp-cat-equipment",categoryName:"صيانة معدات",requestedByEmployeeId:"employee-technician",amount:"1800.00",status:"approved",approvalStatus:"approved",paidStatus:"unpaid",approvedByEmployeeId:"employee-manager",approvedAt:"2026-08-06T12:00:00+03:00",attachments:[{id:"att-3",name:"عرض إصلاح Mock",mockReference:"mock://expense/3"}]}),
  base({id:"expense-paid",expenseNumber:"EXP-2026-0004",branchId:"main",categoryId:"exp-cat-cleaning",categoryName:"نظافة",requestedByEmployeeId:"employee-rental",amount:"450.00",status:"paid",approvalStatus:"approved",paidStatus:"paid",approvedByEmployeeId:"employee-owner",cashboxId:"cash-main",paymentId:"finance-payment-expense-4",approvedAt:"2026-08-05T12:00:00+03:00",paidAt:"2026-08-05T13:00:00+03:00"}),
  base({id:"expense-rejected",expenseNumber:"EXP-2026-0005",branchId:"branch-2",categoryId:"exp-cat-emergency",categoryName:"مصروف طارئ",requestedByEmployeeId:"employee-sales",amount:"900.00",status:"rejected",approvalStatus:"rejected",paidStatus:"unpaid",approvedByEmployeeId:"employee-manager",rejectionReason:"الغرض غير موضح بما يكفي."}),
  base({id:"expense-reimbursement",expenseNumber:"EXP-2026-0006",branchId:"workshop",categoryId:"exp-cat-tools",categoryName:"شراء أدوات",requestedByEmployeeId:"employee-technician",amount:"320.00",status:"pending_approval",approvalStatus:"pending",paidStatus:"unpaid",paidPersonally:true,reimbursementRequested:true}),
  base({id:"expense-attachment",expenseNumber:"EXP-2026-0007",branchId:"main",categoryId:"exp-cat-utilities",categoryName:"كهرباء ومرافق",requestedByEmployeeId:"employee-manager",amount:"2750.00",status:"pending_approval",approvalStatus:"pending",paidStatus:"unpaid",attachments:[{id:"att-7",name:"إيصال مرافق Mock",mockReference:"mock://expense/7"}]}),
  base({id:"expense-reversed",expenseNumber:"EXP-2026-0008",branchId:"main",categoryId:"exp-cat-hospitality",categoryName:"ضيافة إدارية",requestedByEmployeeId:"employee-manager",amount:"380.00",status:"reversed",approvalStatus:"approved",paidStatus:"reversed",approvedByEmployeeId:"employee-owner",cashboxId:"cash-main",paymentId:"finance-payment-expense-8",cancellationReason:"عكس موثق لتكرار السند",approvedAt:"2026-08-04T12:00:00+03:00",paidAt:"2026-08-04T13:00:00+03:00"}),
];

