"use client";
import Link from "next/link";
import {AlertTriangle,ArrowLeft,CheckCircle2,Clock3,ClipboardCheck,PackageCheck,Settings2,Wrench} from "lucide-react";
import {useMemo,useState} from "react";
import {PermissionDeniedState} from "@/components/feedback/PermissionDeniedState";
import {useShell} from "@/components/shell/ShellContext";
import {Badge} from "@/components/ui/Badge";
import {useAttendance} from "@/features/attendance/hooks/use-attendance";
import {resolvePreviewEmployee} from "@/features/employees/fixtures";
import {useExpenses} from "@/features/expenses/hooks/use-expenses";
import {useMaintenance} from "@/features/maintenance/hooks/use-maintenance";
import {useRentalReminderEvaluation} from "@/features/rentals/hooks/use-rental-reminders";
import {useRentals} from "@/features/rentals/hooks/use-rentals";
import {useShifts} from "@/features/shifts/hooks/use-shifts";
import {useTransfers} from "@/features/transfers/hooks/use-transfers";
import {PERMISSION_KEYS} from "@/permissions/keys";
import type {PermissionKey,RoleId} from "@/permissions/types";
type Tone="danger"|"warning"|"info";type Group="urgent"|"review"|"ongoing";type Filter="all"|Group;
interface Task{id:string;title:string;description:string;reference:string;href:string;tone:Tone;group:Group;kind:string}
const labels:Record<Filter,string>={all:"الكل",urgent:"عاجل",review:"ينتظر مراجعة",ongoing:"قيد التنفيذ"};
const doneMaintenance=new Set(["delivered","closed","cancelled"]);const doneTransfer=new Set(["completed","rejected","cancelled"]);
const rentalLabel:Record<string,string>={selecting:"اختيار الأصل",active:"تأجير نشط",near_end:"اقترب الانتهاء",additional_time:"وقت إضافي"};
const maintenanceLabel:Record<string,string>={new:"أمر جديد",awaiting_acknowledgement:"ينتظر الاستلام",acknowledged:"تم الاستلام",inspection_scheduled:"فحص مجدول",diagnosing:"قيد التشخيص",awaiting_customer_approval:"ينتظر موافقة العميل",awaiting_part:"ينتظر قطعة",transfer_requested:"تحويل مطلوب",in_transit_to_workshop:"في الطريق للورشة",received_at_workshop:"وصل الورشة",in_repair:"قيد الإصلاح",quality_check:"فحص الجودة",ready_for_return:"جاهز للعودة",returning_to_branch:"يعود للفرع",ready_for_delivery:"جاهز للتسليم"};
const digits=(value:number)=>value.toLocaleString("en-US");
export function OperationsPage(){const shell=useShell();if(!shell.permissions.has(PERMISSION_KEYS.operations))return <PermissionDeniedState/>;return <Content permissions={shell.permissions} roles={shell.roles} activeBranch={shell.activeBranch.id} branches={shell.availableBranches.map((item)=>item.id)}/>}
function Content({permissions,roles,activeBranch,branches}:{permissions:Set<PermissionKey>;roles:RoleId[];activeBranch:string;branches:string[]}){
 useRentalReminderEvaluation();const rentals=useRentals(),maintenance=useMaintenance(),transfers=useTransfers(),expenses=useExpenses(),attendance=useAttendance(),shifts=useShifts();const employee=resolvePreviewEmployee(roles);const[filter,setFilter]=useState<Filter>("all");
 const tasks=useMemo(()=>{const rows:Task[]=[];const allowed=new Set(branches);const inBranch=(id:string)=>activeBranch!=="all"?id===activeBranch:allowed.has("all")||allowed.has(id);
 if(permissions.has(PERMISSION_KEYS.rentals))rentals.rentals.filter((x)=>["selecting","active","near_end","additional_time"].includes(x.status)&&inBranch(x.branchId)).forEach((x)=>{const urgent=["near_end","additional_time"].includes(x.status);rows.push({id:"r-"+x.id,title:rentalLabel[x.status]||"تأجير مفتوح",description:urgent?"يحتاج متابعة الوقت والتواصل مع العميل.":"التأجير مفتوح ضمن التشغيل الحالي.",reference:x.rentalNumber,href:"/rentals/"+x.id,tone:urgent?"warning":"info",group:urgent?"urgent":"ongoing",kind:"التأجير"})});
 if(permissions.has(PERMISSION_KEYS.maintenance))maintenance.orders.filter((x)=>!doneMaintenance.has(x.status)&&inBranch(x.branchId)).filter((x)=>!roles.includes("maintenance_technician")||roles.length>1||x.assignedTechnicianId===employee.id||!x.assignedTechnicianId).forEach((x)=>{const urgent=["awaiting_acknowledgement","awaiting_customer_approval","awaiting_part"].includes(x.status);rows.push({id:"m-"+x.id,title:maintenanceLabel[x.status]||"أمر صيانة مفتوح",description:x.assignedTechnicianId?"الأمر مسند ويحتاج استكمال المرحلة الحالية.":"لم يتم تعيين فني لهذا الأمر بعد.",reference:x.orderNumber,href:"/maintenance/orders/"+x.id,tone:urgent?"warning":"info",group:urgent?"urgent":"ongoing",kind:"الصيانة"})});
 if(permissions.has(PERMISSION_KEYS.transfersView))transfers.transfers.filter((x)=>!doneTransfer.has(x.status)&&(inBranch(x.sourceLocationId)||inBranch(x.destinationLocationId))).forEach((x)=>{const review=["pending_approval","difference_review"].includes(x.status);rows.push({id:"t-"+x.id,title:x.status==="pending_approval"?"تحويل ينتظر الاعتماد":x.status==="difference_review"?"فرق استلام يحتاج مراجعة":"تحويل قيد التنفيذ",description:x.sourceLocationId+" ← "+x.destinationLocationId,reference:x.transferNumber,href:"/inventory/transfers/"+x.id,tone:review?"warning":"info",group:review?"review":"ongoing",kind:"التحويلات"})});
 if(permissions.has(PERMISSION_KEYS.expensesApprove))expenses.expenses.filter((x)=>["submitted","pending_approval","needs_information"].includes(x.status)&&inBranch(x.branchId)).forEach((x)=>rows.push({id:"e-"+x.id,title:x.status==="needs_information"?"مصروف يحتاج معلومات":"مصروف ينتظر الاعتماد",description:x.categoryName+" · "+Number(x.amount).toLocaleString("en-US")+" ج.م",reference:x.expenseNumber,href:"/expenses",tone:"warning",group:"review",kind:"المصروفات"}));
 if(permissions.has(PERMISSION_KEYS.attendanceReviewException))attendance.exceptions.filter((x)=>x.status==="pending"&&inBranch(x.branchId)).forEach((x)=>rows.push({id:"a-"+x.id,title:"استثناء حضور ينتظر القرار",description:x.reason,reference:x.id,href:"/attendance/exceptions",tone:"warning",group:"review",kind:"الحضور"}));
 if(permissions.has(PERMISSION_KEYS.shiftsReview))shifts.shifts.filter((x)=>x.status==="closing_review"&&inBranch(x.branchId)).forEach((x)=>rows.push({id:"s-"+x.id,title:"فرق وردية ينتظر المراجعة",description:"فرق نقدي "+x.cashDifference.toLocaleString("en-US")+" ج.م",reference:x.shiftNumber,href:"/shifts/"+x.id,tone:"danger",group:"review",kind:"الورديات"}));
 const rank={danger:0,warning:1,info:2};return rows.sort((a,b)=>rank[a.tone]-rank[b.tone])},[permissions,roles,employee.id,rentals,maintenance,transfers,expenses,attendance,shifts,activeBranch,branches]);
 const visible=filter==="all"?tasks:tasks.filter((x)=>x.group===filter);const count=(group:Group)=>tasks.filter((x)=>x.group===group).length;
 return <main className="operations-page"><header className="operations-page__header"><div><span>التشغيل</span><h1>مركز العمليات</h1><p>كل ما يحتاج متابعة الآن، مجمّع حسب الصلاحيات والفرع المحدد.</p></div>{permissions.has(PERMISSION_KEYS.settings)&&<Link className="operations-page__settings" href="/settings"><Settings2 size={18}/> إعدادات السياسات</Link>}</header>
 <section className="operations-kpis" aria-label="ملخص العمليات"><article><i className="all"><ClipboardCheck/></i><div><small>إجمالي المهام</small><strong>{digits(tasks.length)}</strong></div></article><article><i className="urgent"><AlertTriangle/></i><div><small>عاجل</small><strong>{digits(count("urgent"))}</strong></div></article><article><i className="review"><Clock3/></i><div><small>ينتظر مراجعة</small><strong>{digits(count("review"))}</strong></div></article><article><i className="ongoing"><Wrench/></i><div><small>قيد التنفيذ</small><strong>{digits(count("ongoing"))}</strong></div></article></section>
 <section className="operations-workspace"><div className="operations-workspace__toolbar"><div><h2>قائمة المتابعة</h2><p>تتحدث تلقائيًا من حالة الـMock الحالية.</p></div><div className="operations-filters" role="group" aria-label="تصفية المهام">{(Object.keys(labels) as Filter[]).map((key)=><button type="button" key={key} className={filter===key?"is-active":""} onClick={()=>setFilter(key)}>{labels[key]}<span>{digits(key==="all"?tasks.length:count(key))}</span></button>)}</div></div>
 <div className="operations-list">{visible.length?visible.map((task)=><article className={"operation-task operation-task--"+task.tone} key={task.id}><span className="operation-task__marker">{task.kind==="التحويلات"?<PackageCheck/>:task.kind==="الصيانة"?<Wrench/>:<ClipboardCheck/>}</span><div className="operation-task__body"><div><Badge tone={task.tone==="danger"?"danger":task.tone==="warning"?"warning":"info"}>{task.kind}</Badge><code dir="ltr">{task.reference}</code></div><h3>{task.title}</h3><p>{task.description}</p></div><Link href={task.href}>فتح المهمة <ArrowLeft size={17}/></Link></article>):<div className="operations-empty"><CheckCircle2/><h3>لا توجد مهام في هذا التصنيف</h3><p>كل العناصر الحالية منتهية أو خارج نطاق الفرع والصلاحيات.</p></div>}</div></section></main>
}