import { ALL_PERMISSIONS, PERMISSION_KEYS as permission } from "./keys";
import type { RoleId, RoleTemplate } from "./types";

export const ROLE_TEMPLATES: Record<RoleId, RoleTemplate> = {
  owner: {
    id: "owner",
    labelAr: "مالك النشاط",
    shortLabelAr: "المالك",
    permissions: ALL_PERMISSIONS,
    branchIds: "all",
  },
  manager: {
    id: "manager",
    labelAr: "المدير",
    shortLabelAr: "المدير",
    permissions: ALL_PERMISSIONS,
    branchIds: "all",
  },
  rental_maintenance_employee: {
    id: "rental_maintenance_employee",
    labelAr: "موظف التأجير واستلام الصيانة",
    shortLabelAr: "التأجير والصيانة",
    permissions: [
      permission.dashboard,
      permission.operations,
      permission.rentals,
      permission.maintenance,
      permission.maintenanceIntake,
      permission.rentalAssets,
      permission.transfersView,
      permission.transfersCreate,
      permission.transfersOperate,
      permission.branchNeedsView,
      permission.branchNeedsCreate,
      permission.profile,
      permission.attendanceCapture,
      permission.attendanceViewSelf,
      permission.attendanceRequestException,
      permission.shifts,
      permission.shiftsOpen,
      permission.shiftsClose,
      permission.financeCollect,
      permission.expensesCreate,
      permission.expensesViewSelf,
      permission.payrollViewSelf,
      permission.advancesRequest,
      permission.reportsViewSelf,
      permission.notifications,
      permission.auditViewSelf,
    ],
    branchIds: ["main", "branch-2"],
  },
  sales_employee: {
    id: "sales_employee",
    labelAr: "موظف المبيعات",
    shortLabelAr: "المبيعات",
    permissions: [
      permission.dashboard,
      permission.operations,
      permission.sales,
      permission.products,
      permission.inventory,
      permission.inventoryMovements,
      permission.transfersView,
      permission.transfersCreate,
      permission.transfersOperate,
      permission.branchNeedsView,
      permission.branchNeedsCreate,
      permission.profile,
      permission.attendanceCapture,
      permission.attendanceViewSelf,
      permission.attendanceRequestException,
      permission.shifts,
      permission.shiftsOpen,
      permission.shiftsClose,
      permission.financeCollect,
      permission.expensesCreate,
      permission.expensesViewSelf,
      permission.payrollViewSelf,
      permission.advancesRequest,
      permission.reportsViewSelf,
      permission.notifications,
      permission.auditViewSelf,
    ],
    branchIds: ["main", "branch-2", "branch-3"],
  },
  maintenance_technician: {
    id: "maintenance_technician",
    labelAr: "فني الصيانة",
    shortLabelAr: "فني الصيانة",
    permissions: [
      permission.dashboard,
      permission.operations,
      permission.maintenance,
      permission.maintenanceTechnician,
      permission.inventory,
      permission.inventoryMovements,
      permission.transfersView,
      permission.transfersCreate,
      permission.transfersOperate,
      permission.profile,
      permission.attendanceCapture,
      permission.attendanceViewSelf,
      permission.attendanceRequestException,
      permission.expensesCreate,
      permission.expensesViewSelf,
      permission.payrollViewSelf,
      permission.advancesRequest,
      permission.reportsViewSelf,
      permission.notifications,
      permission.auditViewSelf,
    ],
    branchIds: "all",
  },
};
